name: 'Humancat action'
description: 'Generate Human and Cat (GitHub Action Practice)'
inputs:
  human-name:  # id of input
    description: 'human name'
    required: true
    default: 'Ryan'
  cat-name:
    description: 'cat name'
    required: true
    default: 'Haku'
outputs:
  human-name: 
    description: 'The name of Human'
  human-age:
    description: 'Age of Human'
  cat-name:
    description: 'The name of Cat'
  cat-status:
    description: 'Status of Cat'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: cloud-snow
  color: yellow
